// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protoenumstatus/protoenumstatus.proto

package protoenumstatus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusEnum int32

const (
	StatusEnum_UNKNOWN StatusEnum = 0
	StatusEnum_SUCCESS StatusEnum = 1
	StatusEnum_FAILURE StatusEnum = 2
)

// Enum value maps for StatusEnum.
var (
	StatusEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
	}
	StatusEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILURE": 2,
	}
)

func (x StatusEnum) Enum() *StatusEnum {
	p := new(StatusEnum)
	*p = x
	return p
}

func (x StatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protoenumstatus_protoenumstatus_proto_enumTypes[0].Descriptor()
}

func (StatusEnum) Type() protoreflect.EnumType {
	return &file_protoenumstatus_protoenumstatus_proto_enumTypes[0]
}

func (x StatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEnum.Descriptor instead.
func (StatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_protoenumstatus_protoenumstatus_proto_rawDescGZIP(), []int{0}
}

var File_protoenumstatus_protoenumstatus_proto protoreflect.FileDescriptor

const file_protoenumstatus_protoenumstatus_proto_rawDesc = "" +
	"\n" +
	"%protoenumstatus/protoenumstatus.proto\x12\x0fprotoenumstatus*3\n" +
	"\n" +
	"StatusEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02BW\n" +
	"\x0fprotoenumstatusP\x01ZBgithub.com/yylego/protoenum/protos/protoenumstatus;protoenumstatusb\x06proto3"

var (
	file_protoenumstatus_protoenumstatus_proto_rawDescOnce sync.Once
	file_protoenumstatus_protoenumstatus_proto_rawDescData []byte
)

func file_protoenumstatus_protoenumstatus_proto_rawDescGZIP() []byte {
	file_protoenumstatus_protoenumstatus_proto_rawDescOnce.Do(func() {
		file_protoenumstatus_protoenumstatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoenumstatus_protoenumstatus_proto_rawDesc), len(file_protoenumstatus_protoenumstatus_proto_rawDesc)))
	})
	return file_protoenumstatus_protoenumstatus_proto_rawDescData
}

var file_protoenumstatus_protoenumstatus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoenumstatus_protoenumstatus_proto_goTypes = []any{
	(StatusEnum)(0), // 0: protoenumstatus.StatusEnum
}
var file_protoenumstatus_protoenumstatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoenumstatus_protoenumstatus_proto_init() }
func file_protoenumstatus_protoenumstatus_proto_init() {
	if File_protoenumstatus_protoenumstatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoenumstatus_protoenumstatus_proto_rawDesc), len(file_protoenumstatus_protoenumstatus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoenumstatus_protoenumstatus_proto_goTypes,
		DependencyIndexes: file_protoenumstatus_protoenumstatus_proto_depIdxs,
		EnumInfos:         file_protoenumstatus_protoenumstatus_proto_enumTypes,
	}.Build()
	File_protoenumstatus_protoenumstatus_proto = out.File
	file_protoenumstatus_protoenumstatus_proto_goTypes = nil
	file_protoenumstatus_protoenumstatus_proto_depIdxs = nil
}
