// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protoenumresult/protoenumresult.proto

package protoenumresult

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResultEnum defines operation result states
// ResultEnum 定义操作结果状态
type ResultEnum int32

const (
	ResultEnum_UNKNOWN ResultEnum = 0
	ResultEnum_PASS    ResultEnum = 1
	ResultEnum_MISS    ResultEnum = 2
	ResultEnum_SKIP    ResultEnum = 3
)

// Enum value maps for ResultEnum.
var (
	ResultEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "PASS",
		2: "MISS",
		3: "SKIP",
	}
	ResultEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"PASS":    1,
		"MISS":    2,
		"SKIP":    3,
	}
)

func (x ResultEnum) Enum() *ResultEnum {
	p := new(ResultEnum)
	*p = x
	return p
}

func (x ResultEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protoenumresult_protoenumresult_proto_enumTypes[0].Descriptor()
}

func (ResultEnum) Type() protoreflect.EnumType {
	return &file_protoenumresult_protoenumresult_proto_enumTypes[0]
}

func (x ResultEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultEnum.Descriptor instead.
func (ResultEnum) EnumDescriptor() ([]byte, []int) {
	return file_protoenumresult_protoenumresult_proto_rawDescGZIP(), []int{0}
}

var File_protoenumresult_protoenumresult_proto protoreflect.FileDescriptor

const file_protoenumresult_protoenumresult_proto_rawDesc = "" +
	"\n" +
	"%protoenumresult/protoenumresult.proto\x12\x0fprotoenumresult*7\n" +
	"\n" +
	"ResultEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PASS\x10\x01\x12\b\n" +
	"\x04MISS\x10\x02\x12\b\n" +
	"\x04SKIP\x10\x03BW\n" +
	"\x0fprotoenumresultP\x01ZBgithub.com/yylego/protoenum/protos/protoenumresult;protoenumresultb\x06proto3"

var (
	file_protoenumresult_protoenumresult_proto_rawDescOnce sync.Once
	file_protoenumresult_protoenumresult_proto_rawDescData []byte
)

func file_protoenumresult_protoenumresult_proto_rawDescGZIP() []byte {
	file_protoenumresult_protoenumresult_proto_rawDescOnce.Do(func() {
		file_protoenumresult_protoenumresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoenumresult_protoenumresult_proto_rawDesc), len(file_protoenumresult_protoenumresult_proto_rawDesc)))
	})
	return file_protoenumresult_protoenumresult_proto_rawDescData
}

var file_protoenumresult_protoenumresult_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoenumresult_protoenumresult_proto_goTypes = []any{
	(ResultEnum)(0), // 0: protoenumresult.ResultEnum
}
var file_protoenumresult_protoenumresult_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoenumresult_protoenumresult_proto_init() }
func file_protoenumresult_protoenumresult_proto_init() {
	if File_protoenumresult_protoenumresult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoenumresult_protoenumresult_proto_rawDesc), len(file_protoenumresult_protoenumresult_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoenumresult_protoenumresult_proto_goTypes,
		DependencyIndexes: file_protoenumresult_protoenumresult_proto_depIdxs,
		EnumInfos:         file_protoenumresult_protoenumresult_proto_enumTypes,
	}.Build()
	File_protoenumresult_protoenumresult_proto = out.File
	file_protoenumresult_protoenumresult_proto_goTypes = nil
	file_protoenumresult_protoenumresult_proto_depIdxs = nil
}
